### ISSUE TITLE
`winshell` installation does not install

### ISSUE THREAD

**Issue by ffunenga** [tjguk/winshell#11]
After installing winshell with `pip install winshell`, I get the following error:

```python
>>> import winshell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Filipe Funenga\Utilities\filing-cabinet\client\env\lib\site-packages\winshell.py", line 30, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'
```

I followed the installation instructions exactly as explained under the heading "Where do I get it?" in the documentation. What am I doing wrong?

**Comment by rkhwaja** [comment]
You can do `pip install pywin32` to get win32con. Ideally it would be one of the dependencies of this package.
