### ISSUE TITLE
ModuleNotFoundError: No module named 'win32con'

### ISSUE THREAD

**Issue by sr99622** [tjguk/winshell#16]
I have used winshell before successfully, but recently tried an install on a new machine and got the error

```
>>> import winshell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sr996\scratch\Lib\site-packages\winshell.py", line 30, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'
>
```

**Comment by sisoe24** [comment]
It is likely that you need to install `pywin32`. However, in my situation, I encountered additional errors after installing it, which led me to the realization that this library is quite outdated.

**Comment by dimon222** [comment]
`pywin32` dependency is needed. Once you install it, its going to work... `setup.py` of this project should be having it honestly.

**Comment by AreDubya** [comment]
I added a check for this to an installer script I wrote which was breaking in hard-to-decipher ways on user machines. Included below, in case anyone else is getting perplexing reports from users.

```python
def install_package(package_name):
    try:
        print(f"Installing {package_name}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])
        print(f"{package_name} installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error installing {package_name}: {e}")
    except Exception as e:
        print(f"Unexpected & error: Unexpected error: {e}")


try:
    import win32api
    import win32con
except ImportError:
    print("pywin32 not found. Installing...")
    install_package("pypiwin32")
    try:
        import win32api
        import win32con
    except ImportError as e:
        print(f"Error importing pywin32 modules after installation: {e}")
        sys.exit(1)

try:
    import winshell
except ImportError:
    print("winshell not found. Installing...")
    install_package("winshell")
    try:
        import winshell
    except ImportError as e:
        print(f"Error importing winshell after installation: {e}")
        sys.exit(1)
```
