### ISSUE TITLE
Cannot install with Python 3.12

### ISSUE THREAD

**Issue by matkuki** [tjguk/winshell#17]
Hi,

Trying to install on Windows 10 x64 with Python 3.12 I get:
```
Collecting winshell
  Using cached winshell-0.6.zip (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\matic\AppData\Local\Temp\pip-install-u_7fibe4\winshell_ba1976c6af1b4c8f9f21d79f0f0a9f4e\setup.py", line 29, in <module>
          setup (
        File "C:\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\setuptools\dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Python312\Lib\site-packages\setuptools\dist.py", line 679, in finalize_options
          for ep in sorted(loaded, key=by_order):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\setuptools\dist.py", line 678, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
                                 ^^^^^^^^
        File "C:\Python312\Lib\importlib\metadata\__init__.py", line 205, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Python312\Lib\site-packages\cx_Freeze\__init__.py", line 12, in <module>
          from .command.build_exe import BuildEXE as build_exe
        File "C:\Python312\Lib\site-packages\cx_Freeze\command\build_exe.py", line 13, in <module>
          from cx_Freeze.freezer import Freezer
        File "C:\Python312\Lib\site-packages\cx_Freeze\freezer.py", line 30, in <module>
          from .finder import ModuleFinder
        File "C:\Python312\Lib\site-packages\cx_Freeze\finder.py", line 33, in <module>
          IMPORT_STAR = opcode.opmap["IMPORT_STAR"]
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^
      KeyError: 'IMPORT_STAR'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
With Python 3.10 it installs without problems.

**Comment by john-hen** [comment]
It works for me with Python 3.12 on Windows 11. Your error log mentions [cx-Freeze](https://pypi.org/project/cx-Freeze) for reasons unexplained.

**Comment by matkuki** [comment]
@john-hen 
Thanks, removing `cx_freeze`, installing `winshell`, then reinstalling `cx_freeze` worked!
