### ISSUE TITLE
Does not install properly using pip on Python v3.4.2

### ISSUE THREAD

**Issue by joncage** [tjguk/winshell#7]
Install winshell with pip:

    C:\Users\jonc>pip install winshell
    Downloading/unpacking winshell
      Downloading winshell-0.6.zip
      Running setup.py (path:C:\Users\jonc\AppData\Local\Temp\pip_build_Jonc\winshell\setup.py) egg_info for package winshell

    Installing collected packages: winshell
      Running setup.py install for winshell

    Successfully installed winshell
    Cleaning up...

Try and import it:

    C:\Users\jonc>python
    Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import winshell
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python34\lib\site-packages\winshell.py", line 30, in <module>
        import win32con
    ImportError: No module named 'win32con'

Pip version is as follows (does that matter?):

    C:\Users\jonc>pip -V
    pip 1.5.6 from C:\Python34\lib\site-packages (python 3.4)

**Comment by tjguk** [comment]
Thanks for the report; I need to set winshell up to include pip
dependencies. (In particular, to indicate a dependency on the pywin32
packages). The complication is that I don't think pywin32 installs
cleanly under pip because of its complexity.

To work around, install pywin32 first:

http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/

and then winshell should work

**Comment by joncage** [comment]
Hi Tim,

Yeah, manually installing works but it looks like this is a long-standing
issue: https://sourceforge.net/p/pywin32/bugs/680/

Frustrating for us poor Windows Python developers ;-)

Cheers,

Jon
